### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "dadadada@gmail.com",
    "password": "testpassword123"
}

### Sign in a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "dadadada@gmail.com",
    "password": "testpassword123"
}


### Show which user you're logged in as
GET http://localhost:3000/auth/whoami
content-type: application/json

### Sign out a user
POST http://localhost:3000/auth/signout
content-type: application/json


### find a particular user with a given ID
GET http://localhost:3000/auth/1


### find a particular user with a given email
GET http://localhost:3000/auth/?email=tetetete@gmail.com


### remove a particular user with a given id
DELETE http://localhost:3000/auth/1


### update a user
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "tetetete@gmail.com"
}

